name: Python Code Quality

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  schedule:
    - cron: '0 6 * * 1'
      timezone: "America/Los_Angeles"

  workflow_dispatch:

permissions:
  contents: read

jobs:
  ruff:
    name: Ruff Code Quality Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.12"

      - name: Install Ruff
        run: python -m pip install --upgrade ruff

      - name: Show Ruff version
        run: ruff --version

      - name: Run Ruff
        run: |
          ruff check . \
            --exclude "*.ipynb" \
            --exclude "**/psutil/**" \
            --output-format=github
