name: Markdown and Link Check

on:
  push:
    branches:
      - main
    paths:
      - "**/*.md"

  pull_request:
    branches:
      - main
    paths:
      - "**/*.md"

  workflow_dispatch:

permissions:
  contents: read

jobs:
  markdown-links:
    name: Check README Links
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Check Markdown links
        uses: lycheeverse/lychee-action@v2
        with:
          args: >-
            --verbose
            --no-progress
            --accept 200,204,206,429
            "./**/*.md"
          fail: true
